# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpeechEvaluation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpeechEvaluation

   pod 'Starscream', '~> 4.0.0'
   pod "SwiftyXMLParser", :git => 'https://github.com/yahoojapan/SwiftyXMLParser.git'

  target 'SpeechEvaluationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SpeechEvaluationUITests' do
    # Pods for testing
  end

end
